name: Build

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu as the runner environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Use the checkout action to fetch the repository code

      - name: Setup Node.js
        uses: actions/setup-node@v2  # Use the Node.js setup action to set up Node.js environment
        with:
          node-version: '21'  # Specify the Node.js version to use

      - name: Install dependencies
        run: npm install  # Install project dependencies using npm

      - name: Build project
        run: npm run build  # Run the build command for your project

      - name: Archive artifacts
        uses: actions/upload-artifact@v2  # Use the upload artifact action to upload build artifacts
        with:
          name: dist  # Name of the artifact
          path: build/  # Path to the directory containing built files
